// <auto-generated />
using JohanniteLanding.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JohanniteLanding.Data.Migrations
{
    [DbContext(typeof(LinkContext))]
    [Migration("20191210185722_Active")]
    partial class Active
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("JohanniteLanding.Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Href")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("displayName")
                        .HasColumnType("TEXT");

                    b.HasKey("LinkId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            Active = true,
                            Href = "https://office.johannite.tech",
                            displayName = "Divine Office of the Apostolic Johannite Church"
                        },
                        new
                        {
                            LinkId = 2,
                            Active = false,
                            Href = "https://lectionary.johannite.tech",
                            displayName = "The Lectionary of the Apostolic Johannite Church"
                        },
                        new
                        {
                            LinkId = 3,
                            Active = true,
                            Href = "https://johannite.org",
                            displayName = "The Apostolic Johannite Church"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
